export const GET_RESULTS = 'GET_RESULTS';
export const ADD_FAV = 'ADD_FAV';
export const TOGGLE_FAVS_PAGE = 'TOGGLE_FAVS_PAGE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const TOGGLE_COMMENTS = 'TOGGLE_COMMENTS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SUCCESSFUL_AUTH = 'SUCCESSFUL_AUTH';
export const UNSUCCESSFUL_AUTH = 'UNSUCCESSFUL_AUTH';